sudo: required
services:
  - docker

before_install:
  - docker build -t js/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true js/docker-react npm run test

after_success:
  - docker build -t js/docker-client ./client
  - docker build -t js/docker-nginx ./nginx
  - docker build -t js/docker-server ./server
  - docker build -t js/docker-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push -t js/docker-worker
  - docker push -t js/docker-server
  - docker push -t js/docker-client
  - docker push -t js/docker-nginx

#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-1"
#  app: "docker-sample"
#  env: "DockerSample-env"
#  bucket_name: "elasticbeanstalk-us-east-1-877778466778"
#  bucket_path: "docker-sample"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
