sudo: required
services:
  - docker

before_install:
  - docker build -t jinsil/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jinsil/docker-react npm run test

after_success:
  - docker build -t jinsil/docker-client ./client
  - docker build -t jinsil/docker-nginx ./nginx
  - docker build -t jinsil/docker-server ./server
  - docker build -t jinsil/docker-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jinsil/docker-worker
  - docker push jinsil/docker-server
  - docker push jinsil/docker-client
  - docker push jinsil/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-877778466778"
  bucket_path: "muliti-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
